name: CI/CD Workflow

on:
  push:
    branches:
    - master
    paths:
    - 'image-tag'

jobs:
  test:
    name: Build and push image to dockerhub
    runs-on: ubuntu-latest
    steps:
      - name: Checkout master
        uses: actions/checkout@v2

      - name: Setup Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
      
      # - name: Cache Docker layers
      #   uses: actions/cache@v2
      #   with:
      #     path: /tmp/.buildx-cache
      #     key: ${{ runner.os }}-buildx-${{ github.sha }}
      #     restore-keys: |
      #       ${{ runner.os }}-buildx-

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set environment variable
        run: |
          echo "image_tag=$(cat image-tag)" >> $GITHUB_ENV

      # - name: Show environment variable
      #   run: |
      #     echo "Image tag: ${{ env.image_tag }}"

      - name: Set node image on Dockerfile
        run: |
            sed 's|my-docker-tag|node:'"${{ env.image_tag }}"'|g' Dockerfile > dockerfile.image

      # - name: Test image build
      #   uses: docker/build-push-action@v2
      #   with:
      #     no-cache: true
      #     context: ./
      #     file: ./dockerfile.image
      #     push: false
      #     tags: ${{ secrets.DOCKERHUB_USERNAME }}/node-dev/${{ env.image_tag }}

      - name: Push image to dockerhub
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: ./
          file: ./dockerfile.image
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/node-dev:${{ env.image_tag }}

  # deploy:
  #   name: Push image to dockerhub
  #   needs: test
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Set environment variable
  #       run: |
  #         echo "image_tag=$(cat image-tag)" >> $GITHUB_ENV

  #     - name: Show Dockerfile
  #       run: |
  #         cat dockerfile.image

  #     # - name: Build and push
  #     #   id: docker_build
  #     #   uses: docker/build-push-action@v2
  #     #   with:
  #     #     context: ./
  #     #     file: ./dockerfile.image
  #     #     push: true
  #     #     tags: lgdevlop/node-dev/${{ env.image_tag }}
